jobs:
  run_tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet test --filter TestCategory!=DynamoTests

version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2

workflows:
  test_and_deploy:
    jobs:
      - run_tests
      - aws-serverless/deploy:
          name: deploy-backend-staging
          requires:
            - run_tests
          filters:
            branches:
              only:
                - staging
          stack-name: chameleon-game-test
          template: ./template.yaml
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-1hoa4cv2sc075
