jobs:
  run_tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet test --filter TestCategory!=DynamoTests
  deploy:
    executor: aws-serverless/default
    steps:
      - checkout
      - aws-serverless/install
      - run: wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
      - run: sudo dpkg -i packages-microsoft-prod.deb
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https
      - run: sudo apt-get update
      - run: sudo apt-get install dotnet-sdk-2.1
      - run: dotnet tool install -g Amazon.Lambda.Tools
      - run: PATH=$PATH:~/.dotnet/tools sam build -t ./template.yaml --profile default --region $AWS_DEFAULT_REGION
      - run: sam deploy

version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2

workflows:
  test_and_deploy:
    jobs:
      - run_tests
      - deploy:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - staging
